import type { AgentRecord } from "./types";

const now = Date.now();

export const seedAgents: AgentRecord[] = [
  {
    id: "agt_trading_alpha",
    name: "Trading Bot Alpha",
    description: "Executes strategy swaps with strict pre-trade constraints and treasury limits.",
    pdaAddress: "3mG8u2dZr5Qk1pNy7hB4aCv9tE6xWs0LqJ2fVn8M2q",
    status: "trusted",
    trustScore: 82,
    transactionLimitSol: 1.872,
    totalChecks: 142,
    rejectedActions: 7,
    intentCoveragePct: 88,
    createdAt: now - 1000 * 60 * 60 * 24 * 12,
    behavior: "safe",
    decisionHistory: [],
  },
  {
    id: "agt_payment_processor",
    name: "Payment Processor",
    description: "Routes recurring payments to known vendors and verified service addresses.",
    pdaAddress: "9zF4g6k8Qj3nP2x7Yc1mA4uR5wT8bV6dN0hL2sE1kL",
    status: "trusted",
    trustScore: 95,
    transactionLimitSol: 0.623,
    totalChecks: 431,
    rejectedActions: 2,
    intentCoveragePct: 96,
    createdAt: now - 1000 * 60 * 60 * 24 * 40,
    behavior: "safe",
    decisionHistory: [],
  },
  {
    id: "agt_defi_arbitrage",
    name: "DeFi Arbitrage Bot",
    description: "High-frequency routing across pools; behavior shifts with market conditions.",
    pdaAddress: "6dQ2n9eTz8Lk1pNy7hB4aCv9tE6xWs0LqJ2fVn8M4p",
    status: "risky",
    trustScore: 56,
    transactionLimitSol: 0.923,
    totalChecks: 38,
    rejectedActions: 15,
    intentCoveragePct: 61,
    createdAt: now - 1000 * 60 * 60 * 24 * 5,
    behavior: "malicious",
    decisionHistory: [],
  },
  {
    id: "agt_research_oracle",
    name: "Research Oracle",
    description: "Fetches external signals; limited operational history and coverage depth.",
    pdaAddress: "2qZ7u2dZr5Qk1pNy7hB4aCv9tE6xWs0LqJ2fVn8M7x",
    status: "unknown",
    trustScore: 68,
    transactionLimitSol: 0.231,
    totalChecks: 67,
    rejectedActions: 6,
    intentCoveragePct: 72,
    createdAt: now - 1000 * 60 * 60 * 24 * 9,
    behavior: "unknown",
    decisionHistory: [],
  },
  {
    id: "agt_ops_guardian",
    name: "Ops Guardian",
    description: "Protects operations wallet; blocks privilege escalation and anomaly spikes.",
    pdaAddress: "8mNp5k8Qj3nP2x7Yc1mA4uR5wT8bV6dN0hL2sE9aQ",
    status: "trusted",
    trustScore: 90,
    transactionLimitSol: 0.487,
    totalChecks: 204,
    rejectedActions: 4,
    intentCoveragePct: 93,
    createdAt: now - 1000 * 60 * 60 * 24 * 22,
    behavior: "safe",
    decisionHistory: [],
  },
];

